# Generated by Django 5.2.9 on 2025-12-07 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email Address",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone Number")),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Passport Number"
                    ),
                ),
                (
                    "passport_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload passport copy (PDF, JPG, DOCX)",
                        null=True,
                        upload_to="passports/%Y/%m/%d/",
                        verbose_name="Passport File",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(max_length=100, verbose_name="Nationality"),
                ),
                (
                    "country_of_residence",
                    models.CharField(
                        max_length=100, verbose_name="Country of Residence"
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                        ],
                        default="email",
                        max_length=20,
                        verbose_name="Preferred Contact Method",
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("social_media", "Social Media"),
                            ("advertisement", "Advertisement"),
                            ("walk_in", "Walk-in"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=50,
                        verbose_name="Lead Source",
                    ),
                ),
                (
                    "client_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Client Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the client",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="core_client_email_9bd669_idx"),
                    models.Index(
                        fields=["passport_number"],
                        name="core_client_passpor_7c5a65_idx",
                    ),
                    models.Index(
                        fields=["client_status"], name="core_client_client__e91fa8_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="core_client_created_cf382f_idx"
                    ),
                ],
            },
        ),
    ]
