# Generated by Django 5.2.9 on 2025-12-07 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_client_visa_type_alter_client_client_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisaApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visa_type",
                    models.CharField(
                        choices=[
                            ("schengen", "Schengen"),
                            ("us", "US"),
                            ("uk", "UK"),
                            ("au", "AU"),
                            ("nz", "NZ"),
                        ],
                        max_length=20,
                        verbose_name="Visa Type",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("document_collected", "Document Collected"),
                            ("payment_requested", "Payment Requested"),
                            ("payment_received", "Payment Received"),
                            ("appointment_scheduled", "Appointment Scheduled"),
                            ("appointment_attended", "Appointment Attended"),
                            ("waiting_for_decision", "Waiting for Decision"),
                            ("decision_received", "Decision Received"),
                        ],
                        default="initial",
                        max_length=30,
                        verbose_name="Application Stage",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Required when appointment is scheduled",
                        null=True,
                        verbose_name="Appointment Date & Time",
                    ),
                ),
                (
                    "appointment_location",
                    models.CharField(
                        blank=True,
                        help_text="Embassy/Consulate location",
                        max_length=255,
                        null=True,
                        verbose_name="Appointment Location",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Decision",
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Decision Date"
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Decision Notes"
                    ),
                ),
                (
                    "assigned_agent",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Assigned Agent",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Application Notes"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa_applications",
                        to="core.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visa Application",
                "verbose_name_plural": "Visa Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GBP",
                        help_text="Currency code (e.g., GBP, USD, EUR)",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("requested", "Payment Requested"),
                            ("received", "Received"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("cash", "Cash"),
                            ("online_payment", "Online Payment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "payment_requested_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Payment Requested Date"
                    ),
                ),
                (
                    "payment_received_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Payment Received Date"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Bank transaction ID or reference number",
                        max_length=100,
                        null=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Payment Notes"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "visa_application",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link payment to specific visa application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="core.visaapplication",
                        verbose_name="Visa Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="visaapplication",
            index=models.Index(
                fields=["client"], name="core_visaap_client__eff61d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visaapplication",
            index=models.Index(fields=["stage"], name="core_visaap_stage_0f6bdb_idx"),
        ),
        migrations.AddIndex(
            model_name="visaapplication",
            index=models.Index(
                fields=["visa_type"], name="core_visaap_visa_ty_17a422_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visaapplication",
            index=models.Index(
                fields=["decision"], name="core_visaap_decisio_5f37dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visaapplication",
            index=models.Index(
                fields=["appointment_date"], name="core_visaap_appoint_1e97b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visaapplication",
            index=models.Index(
                fields=["-created_at"], name="core_visaap_created_cdd467_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["client"], name="core_paymen_client__e0ca22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["visa_application"], name="core_paymen_visa_ap_cd2408_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_status"], name="core_paymen_payment_e1f577_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_received_date"], name="core_paymen_payment_6e9a5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["-created_at"], name="core_paymen_created_f77624_idx"
            ),
        ),
    ]
