# Generated by Django 5.2.9 on 2025-12-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="visa_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("schengen", "Schengen"),
                    ("us", "US"),
                    ("uk", "UK"),
                    ("au", "AU"),
                    ("nz", "NZ"),
                ],
                help_text="Select the visa type or country",
                max_length=20,
                null=True,
                verbose_name="Visa Type",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_status",
            field=models.CharField(
                choices=[("new", "New"), ("previous", "Previous")],
                default="new",
                max_length=20,
                verbose_name="Client Status",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["visa_type"], name="core_client_visa_ty_b9278e_idx"
            ),
        ),
    ]
