# Generated by Django 5.2.9 on 2025-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_visaapplication_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visaapplication",
            name="decision",
            field=models.CharField(
                blank=True,
                choices=[("approved", "Approved"), ("rejected", "Rejected")],
                max_length=20,
                null=True,
                verbose_name="Decision",
            ),
        ),
    ]
