# Generated by Django 5.2.9 on 2025-12-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_visaapplication_decision"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visa_type",
                    models.CharField(
                        choices=[
                            ("schengen", "Schengen"),
                            ("us", "US"),
                            ("uk", "UK"),
                            ("au", "AU"),
                            ("nz", "NZ"),
                        ],
                        help_text="Select the visa type for this pricing",
                        max_length=20,
                        unique=True,
                        verbose_name="Visa Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for this visa type",
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("GBP", "GBP"), ("USD", "USD"), ("EUR", "EUR")],
                        default="GBP",
                        help_text="Currency for this price",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this pricing is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Pricing",
                "verbose_name_plural": "Pricing",
                "ordering": ["visa_type"],
            },
        ),
        migrations.AddIndex(
            model_name="pricing",
            index=models.Index(fields=["visa_type"], name="core_pricin_visa_ty_idx"),
        ),
        migrations.AddIndex(
            model_name="pricing",
            index=models.Index(fields=["is_active"], name="core_pricin_is_acti_idx"),
        ),
    ]
