# Generated by Django 5.2.9 on 2025-12-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.00,
                help_text="Discount amount (in same currency as payment)",
                max_digits=10,
                verbose_name="Discount",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("referral", "Referral"),
                    ("general", "General"),
                    ("sale", "Sale"),
                ],
                help_text="Type of discount applied",
                max_length=20,
                null=True,
                verbose_name="Discount Type",
            ),
        ),
    ]
