# Generated by Django 5.2.9 on 2025-12-21 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_payment_discount_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Unique invoice number (e.g., INV-2025-001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Invoice Number",
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        help_text="Date when invoice was issued",
                        verbose_name="Invoice Date",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Payment due date",
                        null=True,
                        verbose_name="Due Date",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount before discount and tax",
                        max_digits=10,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Discount amount",
                        max_digits=10,
                        verbose_name="Discount",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Tax rate percentage (e.g., 20.00 for 20%)",
                        max_digits=5,
                        verbose_name="Tax Rate (%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Calculated tax amount",
                        max_digits=10,
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final amount after discount and tax",
                        max_digits=10,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GBP",
                        help_text="Currency code (e.g., GBP, USD, EUR)",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or terms",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when invoice was sent to client",
                        null=True,
                        verbose_name="Sent Date",
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when invoice was paid",
                        null=True,
                        verbose_name="Paid Date",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-invoice_date", "-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="pricing",
            new_name="core_pricin_visa_ty_39c4c2_idx",
            old_name="core_pricin_visa_ty_idx",
        ),
        migrations.RenameIndex(
            model_name="pricing",
            new_name="core_pricin_is_acti_90d91a_idx",
            old_name="core_pricin_is_acti_idx",
        ),
        migrations.AddField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="core.client",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to payment record (if payment received)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice",
                to="core.payment",
                verbose_name="Payment",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="visa_applications",
            field=models.ManyToManyField(
                help_text="Select one or more visa applications for this invoice",
                related_name="invoices",
                to="core.visaapplication",
                verbose_name="Visa Applications",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client"], name="core_invoic_client__f81038_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="core_invoic_invoice_aef6bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="core_invoic_status_3d8780_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_date"], name="core_invoic_invoice_2f1348_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["-created_at"], name="core_invoic_created_ee75a3_idx"
            ),
        ),
    ]
