# Generated by Django 5.2.9 on 2025-12-21 18:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total amount before discount and tax",
                max_digits=10,
                verbose_name="Subtotal",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Final amount after discount and tax",
                max_digits=10,
                verbose_name="Total Amount",
            ),
        ),
    ]
