# Generated by Django 5.2.9 on 2025-12-21 18:59

import django.db.models.deletion
from django.db import migrations, models
from decimal import Decimal


def migrate_existing_data(apps, schema_editor):
    """Migrate existing invoice-visa_application relationships to InvoiceApplication."""
    Invoice = apps.get_model('core', 'Invoice')
    InvoiceApplication = apps.get_model('core', 'InvoiceApplication')
    Pricing = apps.get_model('core', 'Pricing')
    VisaApplication = apps.get_model('core', 'VisaApplication')

    # Get all invoices with visa applications
    for invoice in Invoice.objects.all():
        for visa_app in invoice.visa_applications.all():
            # Get price for this visa application
            try:
                pricing = Pricing.objects.get(visa_type=visa_app.visa_type, is_active=True)
                price = pricing.amount
            except Pricing.DoesNotExist:
                # Default pricing
                if visa_app.visa_type == "schengen":
                    price = Decimal('125.00')
                else:
                    price = Decimal('150.00')

            # Create InvoiceApplication
            InvoiceApplication.objects.get_or_create(
                invoice=invoice,
                visa_application=visa_app,
                defaults={'unit_price': price}
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_invoice_subtotal_alter_invoice_total_amount"),
    ]

    operations = [
        # Step 1: Create InvoiceApplication model
        migrations.CreateModel(
            name="InvoiceApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price at the time of invoice creation",
                        max_digits=10,
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_applications",
                        to="core.invoice",
                    ),
                ),
                (
                    "visa_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_applications",
                        to="core.visaapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Application",
                "verbose_name_plural": "Invoice Applications",
            },
        ),
        # Step 2: Migrate existing data
        migrations.RunPython(migrate_existing_data, migrations.RunPython.noop),
        # Step 3: Remove old M2M field
        migrations.RemoveField(
            model_name="invoice",
            name="visa_applications",
        ),
        # Step 4: Add new M2M field with through
        migrations.AddField(
            model_name="invoice",
            name="visa_applications",
            field=models.ManyToManyField(
                help_text="Select one or more visa applications for this invoice",
                related_name="invoices",
                through="core.InvoiceApplication",
                to="core.visaapplication",
                verbose_name="Visa Applications",
            ),
        ),
        # Step 5: Add indexes and constraints
        migrations.AddIndex(
            model_name="invoiceapplication",
            index=models.Index(
                fields=["invoice"], name="core_invoic_invoice_f10646_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceapplication",
            index=models.Index(
                fields=["visa_application"], name="core_invoic_visa_ap_64db59_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoiceapplication",
            unique_together={("invoice", "visa_application")},
        ),
    ]
