# Generated by Django 5.2.9 on 2026-03-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_invoiceapplication_custom_description'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoiceotherpayment',
            new_name='core_invoic_invoice_09c45d_idx',
            old_name='core_invoic_invoice__b27f64_idx',
        ),
        migrations.RenameIndex(
            model_name='invoiceotherpayment',
            new_name='core_invoic_created_dbefe0_idx',
            old_name='core_invoic_created_5a4a86_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other/Unknown')], default='male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='client',
            name='visa_type',
            field=models.CharField(blank=True, choices=[('schengen', 'Schengen'), ('us', 'US'), ('uk', 'UK'), ('au', 'AU'), ('nz', 'NZ'), ('turkey_evisa', 'Turkey E-visa')], help_text='Select the visa type or country', max_length=20, null=True, verbose_name='Visa Type'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='visa_type',
            field=models.CharField(choices=[('schengen', 'Schengen'), ('us', 'US'), ('uk', 'UK'), ('au', 'AU'), ('nz', 'NZ'), ('turkey_evisa', 'Turkey E-visa')], help_text='Select the visa type for this pricing', max_length=20, unique=True, verbose_name='Visa Type'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='appointment_search_email',
            field=models.EmailField(blank=True, help_text='Email used for appointment searching', max_length=255, null=True, verbose_name='Appointment Search Email'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='appointment_search_website',
            field=models.URLField(blank=True, help_text='Website used to search for appointments', max_length=500, null=True, verbose_name='Appointment Website'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='visa_type',
            field=models.CharField(choices=[('schengen', 'Schengen'), ('us', 'US'), ('uk', 'UK'), ('au', 'AU'), ('nz', 'NZ'), ('turkey_evisa', 'Turkey E-visa')], max_length=20, verbose_name='Visa Type'),
        ),
    ]
