# Generated by Django 5.2.5 on 2026-03-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.BigIntegerField(db_index=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=500)),
                ("institute_name", models.CharField(blank=True, max_length=500)),
                ("campus", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("discipline_name", models.CharField(blank=True, max_length=255)),
                ("specialization_name", models.CharField(blank=True, max_length=255)),
                ("degreelevel_name", models.CharField(blank=True, max_length=255)),
                ("coursetitle_name", models.CharField(blank=True, max_length=255)),
                ("course_language", models.CharField(blank=True, max_length=100)),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("duration_one", models.IntegerField(blank=True, null=True)),
                ("duration_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "course_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("course_fee_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "course_fee_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=20)),
                ("logo", models.TextField(blank=True)),
                ("institute_slug", models.CharField(blank=True, max_length=255)),
                ("course_slug", models.CharField(blank=True, max_length=255)),
                ("clean_course_slug", models.CharField(blank=True, max_length=255)),
                ("program_identifier", models.CharField(blank=True, max_length=100)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("requirements", models.TextField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["course_id"],
                "indexes": [
                    models.Index(
                        fields=["institute_slug"], name="universties_institu_7dae6c_idx"
                    ),
                    models.Index(
                        fields=["discipline_name"],
                        name="universties_discipl_a5bcd5_idx",
                    ),
                    models.Index(
                        fields=["degreelevel_name"],
                        name="universties_degreel_d994b4_idx",
                    ),
                ],
            },
        ),
    ]
